#!/bin/sh

# Device to install on, fill in manually, then remove exit 1
installDevice=
# Partition sizes
efiPartitionSize=512
swapPartitionSize=4096
# System config
timeZone="America/Toronto"
localeGen="en_US.UTF-8 UTF-8"
localeConf="LANG=en_US.UTF-8"
hostName="archlinux"

# Remove this after you've set everything up how you want it
exit 1

read -p "Proceed with installation? This will wipe the device $installDevice (yn) : " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
		#
		# System setup
		#

		# Wipe the device
		dd bs=512 count=1 if=/dev/zero of=$installDevice
		
		echo "	select $installDevice
				mklabel gpt
				mkpart primary 0% $efiPartitionSize
				set 1 esp on
				set 1 bios_grub on
				mkpart primary $efiPartitionSize $swapPartitionSize
				mkpart primary $(($efiPartitionSize + $swapPartitionSize)) 100%" | parted

		efiPartition="${installDevice}1"
		swapPartition="${installDevice}2"
		rootPartition="${installDevice}3"

		# Init partitions
		yes | mkfs.fat $efiPartition
		yes | mkfs.ext4 $rootPartition
		mkswap $swapPartition
		swapon $swapPartition

		# Mount partitions
		mount $rootPartition /mnt
		mkdir -p /mnt/efi
		mount $efiPartition /mnt/efi
		
		#
		# Follow the steps from the arch wiki
		#

		timedatectl set-ntp true
		pacstrap /mnt base base base-devel grub
		genfstab -U /mnt >> /mnt/etc/fstab
			
		echo "#!/bin/sh
		ln -sf /usr/share/zoneinfo/$timeZone /etc/localtime
		hwclock --systohc
		echo $localeGen > /etc/locale.gen
		echo $localeConf > /etc/locale.conf
		echo $hostName > /etc/hostname	
		printf \"127.0.0.1 localhost\n::1 localhost\n127.0.1.1 $hostName.localdomain $hostName\" > /etc/hosts
		# Ask user for the root password
		passwd
		# Finish setup by installing grub
		grub-install --target=i386-pc $installDevice
		grub-mkconfig -o /boot/grub/grub.cfg" > /mnt/finalize.sh
	
		arch-chroot /mnt
fi 

